'Option Strict On
Option Explicit On
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.Net.NetworkInformation

Namespace My

  'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
  ' or if you encounter build errors in this file, go to the Project Designer
  ' (go to Project Properties or double-click the My Project node in
  ' Solution Explorer), and make changes on the Application tab.
  '
  Partial Friend Class MyApplication
    Public ClsLogin_ As New ClsLogin
    <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
    Public Sub New()
      MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
      Me.IsSingleInstance = False
      Me.EnableVisualStyles = True
      Me.SaveMySettingsOnExit = True
      Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
    End Sub

    <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
    Protected Overrides Sub OnCreateMainForm()

      Dim DT As New DataTable
      DT.Clear()
            Dim MAC As String = String.Empty
            Dim NICS() As NetworkInterface = NetworkInterface.GetAllNetworkInterfaces()
      For i As Integer = 0 To NICS.Length - 1
        If NICS(i).GetPhysicalAddress.ToString() <> String.Empty Then
                    MAC += NICS(i).GetPhysicalAddress.ToString()
                End If
      Next
      DT = ClsLogin_.CheckInformation(MAC)
            If DT.Rows.Count > 0 Then
                If DT.Rows(0)(2) = 1 Then
                    My.Settings.Usercode = DT.Rows(0)(0)
                    My.Settings.Username = DT.Rows(0)(1)
                    Me.MainForm = Global.GoldSystem.FrmMain
                Else
                    Me.MainForm = Global.GoldSystem.FrmLogin
                End If
            Else
                Me.MainForm = Global.GoldSystem.FrmLogin
            End If
    End Sub
  End Class
End Namespace
